use aes_gcm::{aead::{Aead, KeyInit}, Aes256Gcm, Nonce};
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use chrono::Utc;
use pbkdf2::pbkdf2_hmac;
use rand::RngCore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{fs, io::Write, path::{Path, PathBuf}, sync::Mutex};
use tauri::{AppHandle, Manager, State};
use uuid::Uuid;
use zip::{write::SimpleFileOptions, ZipWriter};

const ITERATIONS: u32 = 600_000;
const MARKER: &str = "tax-evidence-pack-v1";
#[derive(Default)] pub struct VaultState(Mutex<Option<[u8; 32]>>);
#[derive(Serialize, Deserialize)] struct VaultConfig { salt: String }
#[derive(Serialize, Deserialize, Clone)] pub struct EvidenceItem { id: String, name: String, original_name: String, hash: String, mime: String, size: u64, imported_at: String, tax_year: String, category: String, transaction_ref: String, status: String, note: String }
#[derive(Serialize, Deserialize)] struct VaultIndex { marker: String, items: Vec<EvidenceItem> }

fn vault_dir(app: &AppHandle) -> Result<PathBuf, String> { let dir = app.path().app_data_dir().map_err(|e| e.to_string())?.join("vault"); fs::create_dir_all(dir.join("files")).map_err(|e| e.to_string())?; Ok(dir) }
fn key_from(password: &str, salt: &[u8]) -> [u8; 32] { let mut key = [0; 32]; pbkdf2_hmac::<Sha256>(password.as_bytes(), salt, ITERATIONS, &mut key); key }
fn encrypt(key: &[u8; 32], plain: &[u8]) -> Result<Vec<u8>, String> { let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| e.to_string())?; let mut nonce = [0u8; 12]; rand::thread_rng().fill_bytes(&mut nonce); let mut out = nonce.to_vec(); out.extend(cipher.encrypt(Nonce::from_slice(&nonce), plain).map_err(|_| "Encryption failed".to_string())?); Ok(out) }
fn decrypt(key: &[u8; 32], data: &[u8]) -> Result<Vec<u8>, String> { if data.len() < 13 { return Err("Encrypted data is incomplete".into()); } let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| e.to_string())?; cipher.decrypt(Nonce::from_slice(&data[..12]), &data[12..]).map_err(|_| "Could not decrypt this vault. Check the passphrase.".into()) }
fn active_key(state: &VaultState) -> Result<[u8; 32], String> { state.0.lock().map_err(|_| "Vault lock unavailable")?.ok_or_else(|| "Open your vault first".into()) }
fn index_path(app: &AppHandle) -> Result<PathBuf, String> { Ok(vault_dir(app)?.join("index.bin")) }
fn read_index(app: &AppHandle, key: &[u8; 32]) -> Result<VaultIndex, String> { let path = index_path(app)?; if !path.exists() { return Ok(VaultIndex { marker: MARKER.into(), items: vec![] }); } let data = decrypt(key, &fs::read(path).map_err(|e| e.to_string())?)?; let index: VaultIndex = serde_json::from_slice(&data).map_err(|_| "Vault index is invalid".to_string())?; if index.marker != MARKER { return Err("This is not a Tax Evidence Pack vault".into()); } Ok(index) }
fn write_index(app: &AppHandle, key: &[u8; 32], index: &VaultIndex) -> Result<(), String> { let bytes = serde_json::to_vec(index).map_err(|e| e.to_string())?; fs::write(index_path(app)?, encrypt(key, &bytes)?).map_err(|e| e.to_string()) }
fn friendly_name(path: &Path) -> String { path.file_stem().and_then(|x| x.to_str()).unwrap_or("Evidence").replace(['_', '-'], " ") }
fn mime_for(path: &Path) -> String { match path.extension().and_then(|x| x.to_str()).unwrap_or("").to_ascii_lowercase().as_str() { "pdf" => "application/pdf", "jpg" | "jpeg" => "image/jpeg", "png" => "image/png", "heic" => "image/heic", "csv" => "text/csv", _ => "application/octet-stream" }.into() }

#[tauri::command]
fn unlock_vault(app: AppHandle, state: State<VaultState>, password: String) -> Result<(), String> { let dir = vault_dir(&app)?; let path = dir.join("vault.json"); let salt = if path.exists() { serde_json::from_slice::<VaultConfig>(&fs::read(&path).map_err(|e| e.to_string())?).map_err(|e| e.to_string())?.salt } else { let mut raw = [0u8; 16]; rand::thread_rng().fill_bytes(&mut raw); let config = VaultConfig { salt: B64.encode(raw) }; fs::write(&path, serde_json::to_vec(&config).map_err(|e| e.to_string())?).map_err(|e| e.to_string())?; config.salt }; let key = key_from(&password, &B64.decode(salt).map_err(|_| "Vault salt is invalid")?); let index = read_index(&app, &key)?; write_index(&app, &key, &index)?; *state.0.lock().map_err(|_| "Vault lock unavailable")? = Some(key); Ok(()) }
#[tauri::command] fn list_evidence(app: AppHandle, state: State<VaultState>) -> Result<Vec<EvidenceItem>, String> { Ok(read_index(&app, &active_key(&state)?)?.items) }
#[tauri::command]
fn import_files(app: AppHandle, state: State<VaultState>, tax_year: String, category: String, transaction_ref: String) -> Result<usize, String> { let files = rfd::FileDialog::new().set_title("Add evidence to your encrypted binder").add_filter("Evidence files", &["pdf", "png", "jpg", "jpeg", "heic", "csv"]).pick_files().unwrap_or_default(); let key = active_key(&state)?; let mut index = read_index(&app, &key)?; let dir = vault_dir(&app)?; let mut added = 0; for path in files { let bytes = fs::read(&path).map_err(|_| format!("Could not read {}", path.display()))?; let hash = hex::encode(Sha256::digest(&bytes)); let id = Uuid::new_v4().to_string(); fs::write(dir.join("files").join(format!("{id}.bin")), encrypt(&key, &bytes)?).map_err(|e| e.to_string())?; let original = path.file_name().and_then(|x| x.to_str()).unwrap_or("original").to_string(); index.items.push(EvidenceItem { id, name: friendly_name(&path), original_name: original, hash, mime: mime_for(&path), size: bytes.len() as u64, imported_at: Utc::now().to_rfc3339(), tax_year: tax_year.clone(), category: category.clone(), transaction_ref: transaction_ref.clone(), status: "supported".into(), note: String::new() }); added += 1; } write_index(&app, &key, &index)?; Ok(added) }
#[tauri::command]
fn add_missing_evidence(app: AppHandle, state: State<VaultState>, tax_year: String, name: String, category: String, transaction_ref: String) -> Result<(), String> { let key = active_key(&state)?; let mut index = read_index(&app, &key)?; index.items.push(EvidenceItem { id: Uuid::new_v4().to_string(), name, original_name: String::new(), hash: "missing-evidence".into(), mime: String::new(), size: 0, imported_at: Utc::now().to_rfc3339(), tax_year, category, transaction_ref, status: "missing".into(), note: "Evidence has not been attached yet".into() }); write_index(&app, &key, &index) }
#[tauri::command]
fn delete_evidence(app: AppHandle, state: State<VaultState>, id: String) -> Result<(), String> { let key = active_key(&state)?; let mut index = read_index(&app, &key)?; if let Some(pos) = index.items.iter().position(|i| i.id == id) { index.items.remove(pos); let file = vault_dir(&app)?.join("files").join(format!("{id}.bin")); if file.exists() { fs::remove_file(file).map_err(|e| e.to_string())?; } write_index(&app, &key, &index)?; } Ok(()) }
fn pdf_escape(value: &str) -> String { value.replace('\\', "\\\\").replace('(', "\\(").replace(')', "\\)") }
fn simple_pdf(year: &str, items: &[EvidenceItem]) -> Vec<u8> { let mut lines = vec![format!("Tax Evidence Pack — {} review index", year), "Original files and SHA-256 fingerprints are enclosed in this ZIP.".into(), String::new()]; for item in items { lines.push(format!("{} | {} | {} | {} | {}", item.name, item.category, item.transaction_ref, item.status, item.hash)); } let content = lines.iter().enumerate().map(|(n, x)| format!("BT /F1 {} Tf 48 {} Td ({}) Tj ET", if n == 0 { 16 } else { 9 }, 770i32 - (n as i32 * 15), pdf_escape(x))).collect::<Vec<_>>().join("\n"); let objects = vec!["<< /Type /Catalog /Pages 2 0 R >>".to_string(), "<< /Type /Pages /Kids [3 0 R] /Count 1 >>".to_string(), "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>".to_string(), format!("<< /Length {} >>\nstream\n{}\nendstream", content.len(), content), "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".to_string()]; let mut bytes = b"%PDF-1.4\n".to_vec(); let mut offsets = vec![0usize]; for (i, object) in objects.iter().enumerate() { offsets.push(bytes.len()); bytes.extend_from_slice(format!("{} 0 obj\n{}\nendobj\n", i + 1, object).as_bytes()); } let xref = bytes.len(); bytes.extend_from_slice(format!("xref\n0 {}\n0000000000 65535 f \n", objects.len() + 1).as_bytes()); for offset in offsets.iter().skip(1) { bytes.extend_from_slice(format!("{:010} 00000 n \n", offset).as_bytes()); } bytes.extend_from_slice(format!("trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{}\n%%EOF", objects.len() + 1, xref).as_bytes()); bytes }
#[tauri::command]
fn export_pack(app: AppHandle, state: State<VaultState>, tax_year: String) -> Result<String, String> { let key = active_key(&state)?; let index = read_index(&app, &key)?; let items: Vec<_> = index.items.into_iter().filter(|i| i.tax_year == tax_year).collect(); let path = rfd::FileDialog::new().set_file_name(format!("tax-evidence-pack-{}.zip", tax_year)).save_file().ok_or("Export cancelled")?; let file = fs::File::create(&path).map_err(|e| e.to_string())?; let mut zip = ZipWriter::new(file); let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated); zip.start_file(format!("Tax Evidence Pack {} index.pdf", tax_year), options).map_err(|e| e.to_string())?; zip.write_all(&simple_pdf(&tax_year, &items)).map_err(|e| e.to_string())?; for item in items.iter().filter(|i| i.status == "supported") { let encrypted = fs::read(vault_dir(&app)?.join("files").join(format!("{}.bin", item.id))).map_err(|_| format!("Missing encrypted file for {}", item.name))?; let original = decrypt(&key, &encrypted)?; let safe = item.original_name.replace(['/', '\\'], "_"); zip.start_file(format!("originals/{}-{}", item.id, safe), options).map_err(|e| e.to_string())?; zip.write_all(&original).map_err(|e| e.to_string())?; } zip.finish().map_err(|e| e.to_string())?; Ok(path.display().to_string()) }
pub fn run() { tauri::Builder::default().manage(VaultState::default()).invoke_handler(tauri::generate_handler![unlock_vault, list_evidence, import_files, add_missing_evidence, delete_evidence, export_pack]).run(tauri::generate_context!()).expect("error while running Tax Evidence Pack"); }
